import("https://cdn.jsdelivr.net/npm/lodash-es@4.17.21/lodash.js").then(m=>console.log("lodash loaded")).catch(console.error);
import("https://unpkg.com/axios/dist/axios.min.js").then(()=>console.log("axios ok")).catch(console.error);
import("https://esm.sh/react").then(()=>console.log("react ok")).catch(console.error);
fetch("https://cdn.jsdelivr.net/npm/lodash-es@4.17.21/lodash.js").then(r=>r.text()).then(t=>console.log(t.slice(0,100)));
fetch("https://unpkg.com/axios/dist/axios.min.js").then(r=>console.log(r.status));
fetch("https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js").then(r=>r.text()).then(console.log);
let s1=document.createElement("script");s1.src="https://cdn.jsdelivr.net/npm/dayjs/dayjs.min.js";document.body.appendChild(s1);
let s2=document.createElement("script");s2.src="https://unpkg.com/lodash/lodash.min.js";document.body.appendChild(s2);
let s3=document.createElement("script");s3.src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js";document.body.appendChild(s3);
let img1=new Image();img1.src="https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/javascript.svg";document.body.appendChild(img1);
let img2=new Image();img2.src="https://unpkg.com/react@18/umd/react.production.min.js";
let link=document.createElement("link");link.rel="stylesheet";link.href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css";document.head.appendChild(link);
let iframe1=document.createElement("iframe");iframe1.src="https://cdn.jsdelivr.net";document.body.appendChild(iframe1);
let iframe2=document.createElement("iframe");iframe2.src="https://unpkg.com";document.body.appendChild(iframe2);
fetch("https://esm.sh/v135/lodash").then(r=>r.text()).then(console.log);
import("https://esm.sh/v135/axios").then(()=>console.log("esm axios ok"));
let s4=document.createElement("script");s4.src="https://esm.sh/v135/dayjs";document.body.appendChild(s4);
fetch("https://assets.claude.ai").then(r=>console.log("claude reachable?",r.status)).catch(console.error);
new Image().src="https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/github.svg";
fetch("https://cdn.jsdelivr.net/npm/uuid@9.0.0/dist/index.min.js").then(r=>r.text()).then(console.log);
import("https://cdn.jsdelivr.net/npm/uuid@9.0.0/dist/esm-browser/index.js").then(m=>console.log(m));
let s5=document.createElement("script");s5.src="https://cdn.jsdelivr.net/npm/uuid@9.0.0/dist/umd/uuidv4.min.js";document.body.appendChild(s5);
fetch("https://unpkg.com/uuid@9.0.0/dist/index.js").then(r=>r.text()).then(console.log);
import("https://unpkg.com/uuid@9.0.0/dist/esm-browser/index.js").then(console.log);
let s6=document.createElement("script");s6.src="https://cdnjs.cloudflare.com/ajax/libs/uuid/8.3.2/uuid.min.js";document.body.appendChild(s6);
fetch("https://cdnjs.cloudflare.com/ajax/libs/uuid/8.3.2/uuid.min.js").then(r=>r.text()).then(console.log);
import("https://esm.sh/uuid").then(console.log);
let s7=document.createElement("script");s7.src="https://esm.sh/uuid";document.body.appendChild(s7);
fetch("https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js").then(r=>r.text()).then(console.log);
import("https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js").then(()=>console.log("axios loaded"));
let s8=document.createElement("script");s8.src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js";document.body.appendChild(s8);
fetch("https://unpkg.com/react@18/umd/react.production.min.js").then(r=>r.text()).then(console.log);
import("https://esm.sh/react@18").then(console.log);
let s9=document.createElement("script");s9.src="https://unpkg.com/react@18/umd/react.production.min.js";document.body.appendChild(s9);
fetch("https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js").then(r=>r.text()).then(console.log);
import("https://esm.sh/vue@3").then(console.log);
let s10=document.createElement("script");s10.src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js";document.body.appendChild(s10);
fetch("https://cdn.jsdelivr.net/npm/chart.js").then(r=>r.text()).then(console.log);
import("https://esm.sh/chart.js").then(console.log);
let s11=document.createElement("script");s11.src="https://cdn.jsdelivr.net/npm/chart.js";document.body.appendChild(s11);
fetch("https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js").then(r=>r.text()).then(console.log);
let s12=document.createElement("script");s12.src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js";document.body.appendChild(s12);
import("https://esm.sh/three").then(console.log);
fetch("https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js").then(r=>r.text()).then(console.log);
let s13=document.createElement("script");s13.src="https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js";document.body.appendChild(s13);
import("https://esm.sh/d3").then(console.log);
fetch("https://unpkg.com/d3@7/dist/d3.min.js").then(r=>r.text()).then(console.log);
let s14=document.createElement("script");s14.src="https://unpkg.com/d3@7/dist/d3.min.js";document.body.appendChild(s14);
